# WordCamp Brisbane Configuration
hosts:
    - wordcamp.local

# Database configuration
# (When overriding, include all values)
database:
    name: wordcamp
    user: wordcamp
    password: vagrantpassword
    prefix: wc_

# Admin configuration
# (When overriding, include all values)
admin:
    user: wordcamp
    email: bronson@wordcamp.org
    password: qCTMbf8){kUZWk8xk

# Extensions
#
# Install a list of extensions automatically
extensions:
  # https://github.com/Chassis/MailHog
  - chassis/mailhog
  # https://github.com/Chassis/Xdebug
  - chassis/xdebug
  # https://github.com/Chassis/Tester
  - chassis/tester
  # https://github.com/Chassis/Composer
  - chassis/composer
  # https://github.com/Chassis/Grunt
  - chassis/grunt

# PHP version
# Values: 5.6, 7.0, 7.1 (or 5.6.30)
php: 7.1
